name: ZAP Baseline DAST Scan

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - feature/dast  # ou ta branche principale

env:
  REGION: europe-west1
  DOCKER_IMAGE: darklyx/myapp:dev-${{ github.sha }}

jobs:
  zap_scan:
    name: ZAP Baseline Scan
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ env.DOCKER_IMAGE }}

      - name: Run application container
        run: |
          docker run -d --name myapp-test -p 8080:8080 ${{ env.DOCKER_IMAGE }}
          sleep 10

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8080'
          time: '1'
          format: 'json'
          output: 'zap_report.json'
          fail_action: false

      - name: Upload ZAP scan report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.json

      - name: Stop and remove application container
        if: always()
        run: |
          docker stop myapp-test
          docker rm myapp-test
